config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # resources :home %i[index]
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#index'
  resources :users do
    resources :categories do
      resources :transacs
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transacs, dependent: :destroy
  validates :name, :icon, presence: true
end

app/models/transac.rb
class Transac < ApplicationRecord
  belongs_to :category
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  has_many :categories, dependent: :destroy
  has_many :transacs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # , :except
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end

  def authenticate_user!
    if user_signed_in?
      super
    elsif request.original_fullpath != home_index_path
      redirect_to home_index_path,
                  notice: 'Please Login to view that page!'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories
  end

  def show
    @category = current_user.categories.find(params[:id])
    @transacs = @category.transacs
    # sum all transac
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category.save

      redirect_to user_categories_path
    else
      flash[:alert] = 'icon && name should not be empty'
      render :new
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @Category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/transacs_controller.rb
class TransacsController < ApplicationController
  before_action :authenticate_user!
  def index
    @transacs = current_user.categories.find(params[:category_id]).transacs
  end

  def show
    @transacs = current_user.categories.find(params[:category_id]).transacs.find(params[:id])
  end

  def new
    @categories = current_user.categories
    @transac = current_user.categories.find(params[:category_id]).transacs.new
  end

  def create
    @categories = current_user.categories
    @transac = @categories.find(params[:category_id]).transacs.create(transac_params)
    @transac.save
    redirect_to user_category_path(current_user, params[:category_id])
    # if @transac.save
    #   redirect_to user_category_path(current_user, )
    # else
    #   render :new
    # end
  end

  def destroy
    @transac = current_user.categories.find(params[:category_id]).transacs.find(params[:transac_id])
    @transac.destroy
    redirect_to category_transacs_path(@transac.category_id)
  end

  private

  def transac_params
    params.require(:transac).permit(:amount, :name, :category_id)
  end
end

app/controllers/transactions_controller.rb
class TransacsController < ApplicationController
  def index
    @transacs = current_user.categories.find(params[:category_id]).transacs
  end

  def show
        @transacs = current_user.categories.find(params[:category_id]).transacs.find(params[:transac_id])
  end

  def new
    @transac = current_user.categories.find(params[:category_id]).transacs.new
  end

  def create
    @transac = current_user.categories.find(params[:category_id]).transacs.create(transac_params)
    if @transac.save
      redirect_to category_transacs_path(@transac.category_id)
    else
      render :new
    end
  end

  def destroy
    @transac = current_user.categories.find(params[:category_id]).transacs.find(params[:transac_id])
    @transac.destroy
    redirect_to category_transacs_path(@transac.category_id)
  end
    @transac.destroy
    redirect_to category_transacs_path(@transac.category_id)
  end

  private

  def transac_params
    params.require(:transac).permit(:amount, :name,  :category_id)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transacs_helper.rb
module TransacsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<section class="categories">
<header class="d-flex justify-content-between align-items-center bg-primary text-white py-2 px-3">
     <div>
     <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <h2 class= "justify-self-center">CATEGORIES</h2>
    <div>
    <%= link_to destroy_user_session_path, class:'text-white', :method => :delete do %>
         <i class="fas fa-sign-out-alt "></i>
    <% end %>
    </div>
  </header>


<ul class="d-flex categories-ul flex-column align-items-center">
    <% @categories.each do |category| %>
        <li class="category ">
            <%= link_to user_category_path(category.user, category), class: ' list-group-item d-flex justify-content-between align-items-center' do %>
                <div class="h-100 py-2 d-flex justify-content-between align-items-center ">
                    <img src="<%= category.icon %>" class="h-75 rounded"/>
                    <div class="text-secondary ml-2 p-2">
                        <p class="mb-3 text-capitalize"><%= category.name %></p>
                        <p class="smal-txt"><%= category.created_at.strftime("%d %b %Y") %> </p>

                    </div>
                </div>
                
                <div class="fw-bold">
                    <%= number_to_currency(category.transacs.sum(:amount))%>
                </div>
            <% end %>
        </li>
    <% end %>
</ul>

<div class="scan">
<%= link_to "ADD NEW CATEGORY", new_user_category_path(current_user) %>

</div>
</section>

app/views/categories/new.html.erb
<section class="sign-up">
  <header class="d-flex mb-3 justify-content-between align-items-center bg-primary text-white">
    <%= link_to root_path, class: "text-white" do %>
     <i class="fa fa-arrow-left" aria-hidden="true"></i>
    <%end%>
    <h2 class= "justify-self-center">NEW CATEGORY</h2>
    <div></div>
  </header>

  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %> 

 <%= form_with(model: @category, url: { action: "create" }, class: "border-top border-2") do |form| %>
  <div class="field">
    <%= form.text_field :icon, autofocus: true, placeholder: "Icon", autocomplete: "", class: ""%>
  </div>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name", class: "border-top border-2" %>
  </div>

  <div class="actions">
  <%= form.submit "SAVE" %>
  </div>
<% end %>
</section>

app/views/categories/show.html.erb
<section class="categories">
<header class="d-flex justify-content-between align-items-center bg-primary text-white py-2 px-3">
     <div>
        <%= link_to root_path, class: "text-white" do %>
            <i class="fa fa-bars" aria-hidden="true"></i>
        <% end %>
    </div>
    <h2 class= "justify-self-center">TRANSACTIONS</h2>
    <div>
    <%= link_to destroy_user_session_path, class:'text-white', :method => :delete do %>
         <i class="fas fa-sign-out-alt "></i>
    <% end %>
    </div>
  </header>


<div class="bg-white py-4 px-2">
   Total amount: <span class="fw-bold"> <%= number_to_currency(@category.transacs.sum(:amount)) %></span>
</div>

<ul class="d-flex categories-ul flex-column align-items-center">
    <%  @transacs.each do |transac| %>
        <li class="transac list-group-item d-flex justify-content-between m-3">
                <div>
                    <p class="mb-3 text-capitalize"><%= transac.name %></p>
                    <p class="smal-txt text-secondary"><%= transac.created_at.strftime("%d %B %Y") %> at <%= transac.created_at.strftime("%H:%M") %></p>
                </div>                              
                <div class="my-2">
                     <span class="fw-bold"> <%= number_to_currency(transac.amount) %></span>
                </div>
        </li>
    <% end %>
</ul>

<div class="scan">
<%= link_to "ADD NEW TRANSACTION", new_user_category_transac_path(current_user, @category) %>

</div>
</section>

app/views/home/index.html.erb
<section class="d-flex flex-column home align-items-center justify-content-end py-5">

    <h1>MyBudgetApp</h1>
    <div class="btn-sign-in my-2">
         <%= link_to "LOG IN", new_user_session_path, class: "btn btn-primary w-100" %>
    </div>
    <div class="pb-5">
         <%= link_to "SIGN UP", new_user_registration_path %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transacs/create.html.erb
<h1>Transacs#create</h1>
<p>Find me in app/views/transacs/create.html.erb</p>

app/views/transacs/destroy.html.erb
<h1>Transacs#destroy</h1>
<p>Find me in app/views/transacs/destroy.html.erb</p>

app/views/transacs/index.html.erb
<h1>Transacs#index</h1>
<p>Find me in app/views/transacs/index.html.erb</p>

app/views/transacs/new.html.erb
<section class="sign-up">
  <header class="d-flex mb-3 justify-content-between align-items-center bg-primary text-white">
    <%= link_to root_path, class: "text-white" do %>
     <i class="fa fa-arrow-left" aria-hidden="true"></i>
    <%end%>
    <h2 class= "justify-self-center">NEW TRANSACTION</h2>
    <div></div>
  </header>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %> 

 <%= form_with(model: @transac, url: { action: "create" }) do |form| %>
  <div class="field">
    <%= form.text_field :name, autofocus: true, placeholder: "Name", autocomplete: "", class: ""%>
  </div>

  <div class="field">
    <%= form.text_field :amount, placeholder: "Amount", class: "border-top border-2" %>
  </div>

    <div class="field">
        <%= form.select :category_id, @categories.map { |t| [t.name, t.id]}, {}, class: 'form-control mb-3 mt-3', placeholder:'Category' %>
    </div>


  <div class="actions">
  <%= form.submit "SAVE" %>
  </div>
<% end %>
</section>

app/views/transacs/show.html.erb
<h1>Transacs#show</h1>
<p>Find me in app/views/transacs/show.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>